/*******************************************************************************
* Copyright (C) 2019-2023 Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

// planeshipnet
// This file was @generated by ai8xize.py --test-dir synthed_net --prefix planeshipnet --checkpoint-file trained/planeshipnet_trained-q.pth.tar --config-file networks/planeshipnet.yaml --sample-input tests/sample_planeships.npy --softmax --device MAX78000 --compact-data --mexpress --timer 0 --display-checkpoint --verbose --overwrite

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "mxc.h"
#include "cnn.h"
#include "app.h"
#include "uart.h"
// #include "mxc_device.h"
// #include "nvic_table.h"
// #include "board.h"
#include "mxc_device.h"
#include "led.h"
#include "board.h"
#include "mxc_delay.h"
#include "dma.h"
#include "nvic_table.h"

volatile uint32_t cnn_time; // Stopwatch

void fail(void)
{
  printf("\n*** FAIL ***\n\n");
  while (1);
}

// 3-channel 20x20 data input (1200 bytes total / 400 bytes per channel):
// HWC 20x20, channels 0 to 2

// Expected output of layer 4 for planeshipnet given the sample input (known-answer test)
// Delete this function for production code

#define UART_BAUD 115200
#define BUFF_SIZE 2048

#define UART 0

uint8_t init_uart() {

    printf("Initializing UART on UART%d with baud %u\n", UART, UART_BAUD);
    // MXC_UART_Init(MXC_UART0, 115200, MXC_SYS_PERIPH_CLOCK_UART0);

    // Enable UART
    // MXC_UART_Enable(UART);


    int error = 0;

    // Initialize the UART
    if ((error = MXC_UART_Init(MXC_UART_GET_UART(UART), UART_BAUD, MXC_UART_APB_CLK)) !=
        E_NO_ERROR) {
        printf("-->Error initializing UART: %d\n", error);
        // printf("-->Example Failed\n");
        return error;
    }
    
    return 0;
}



int main(void)
{
  LED_Init();
    LED_On(LED_GREEN);
  MXC_ICC_Enable(MXC_ICC0); // Enable cache


  // if(init_uart() != 0) {
  //   printf("Failed to initialize UART! :(");
  //   return 1;
  // }


  // Switch to 100 MHz clock
  MXC_SYS_Clock_Select(MXC_SYS_CLOCK_IPO);
  SystemCoreClockUpdate();


  //printf("Waiting...\n");

  // DO NOT DELETE THIS LINE:
  MXC_Delay(SEC(2)); // Let debugger interrupt if needed

 

  
  app();

  //MXC_ICC_Flush(MXC_ICC0);
  //MXC_ICC_Flush(MXC_ICC1);

  return 0;
}

/*
  SUMMARY OF OPS
  Hardware: 1,329,192 ops (1,302,592 macc; 26,600 comp; 0 add; 0 mul; 0 bitwise)
    Layer 0: 268,800 ops (259,200 macc; 9,600 comp; 0 add; 0 mul; 0 bitwise)
    Layer 1: 704,000 ops (691,200 macc; 12,800 comp; 0 add; 0 mul; 0 bitwise)
    Layer 2: 292,200 ops (288,000 macc; 4,200 comp; 0 add; 0 mul; 0 bitwise)
    Layer 3: 64,000 ops (64,000 macc; 0 comp; 0 add; 0 mul; 0 bitwise)
    Layer 4: 192 ops (192 macc; 0 comp; 0 add; 0 mul; 0 bitwise)

  RESOURCE USAGE
  Weight memory: 83,272 bytes out of 442,368 bytes total (18.8%)
  Bias memory:   67 bytes out of 2,048 bytes total (3.3%)
*/

